// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.user_id", "cb2e6406-6593-49e1-b4dc-6c34bd107101");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1572853405);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1572853525);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1572853645);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1572853375);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 86);
user_pref("browser.newtabpage.activity-stream.impressionId", "{30e2b7a7-2a71-4290-a833-15e71f0dc569}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1572853424569");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1572855224569");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1572853380830");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1572856980830");
user_pref("browser.search.region", "PL");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1572853376");
user_pref("browser.slowStartup.averageTime", 2309);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20190919142304");
user_pref("browser.startup.homepage_override.mstone", "69.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1572853376);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\",\"ublock0_raymondhill_net-browser-action\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"ublock0_raymondhill_net-browser-action\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.fedora.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "69.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "b36a9dc6001646b0901c5caddbd7925c");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "69.0.1");
user_pref("extensions.lastPlatformVersion", "69.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.uBlock0@raymondhill.net", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"e9d66665-77c9-411b-877b-133e978acf2a\",\"fxmonitor@mozilla.org\":\"13464c65-594e-49e8-911c-f50fa236d02e\",\"screenshots@mozilla.org\":\"998e6676-b0bf-4a79-b720-dcd60ca1009a\",\"webcompat-reporter@mozilla.org\":\"fdd17a62-68bd-4cee-804a-a46219b37890\",\"webcompat@mozilla.org\":\"7638238b-de8b-4b0f-aabc-fca474014c76\",\"uBlock0@raymondhill.net\":\"854f122e-3fa2-4685-a657-35d07660d535\",\"default-theme@mozilla.org\":\"0a4a86a0-1550-4616-8c0e-06598a45014b\",\"google@search.mozilla.org\":\"86c98334-582c-426e-a79a-d42d6cd0ab45\",\"amazondotcom@search.mozilla.org\":\"8a84ae46-cc9c-4e75-92eb-99c75dd384c5\",\"bing@search.mozilla.org\":\"ca20aa2d-27f9-4e08-919b-ec8764ce5574\",\"ddg@search.mozilla.org\":\"39c107ec-8b20-4ed0-bcfa-833cbdf7d4b0\",\"ebay@search.mozilla.org\":\"284ea18e-f741-426d-bef9-e377395a7e02\",\"twitter@search.mozilla.org\":\"e3bf41f7-0e96-45ad-b97e-d84a3a6780d4\",\"wikipedia@search.mozilla.org\":\"74483cce-ab5a-40ce-8109-bb143c606bbd\"}");
user_pref("idle.lastDailyNotification", 1572853599);
user_pref("media.gmp-manager.buildID", "20190919142304");
user_pref("media.gmp-manager.lastCheck", 1572853398);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.dns.disablePrefetch", true);
user_pref("network.http.speculative-parallel-limit", 0);
user_pref("network.predictor.enabled", false);
user_pref("network.prefetch-next", false);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1572853599);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "c85695b4-89cc-4382-82fc-dff19e6f61e3");
user_pref("security.sandbox.plugin.tempDirSuffix", "4eaf9bdb-dff1-4ea6-aeb8-15d6ec9f5eb3");
user_pref("services.blocklist.pinning.checked", 1572853397);
user_pref("services.settings.clock_skew_seconds", -4);
user_pref("services.settings.last_etag", "\"1572653775258\"");
user_pref("services.settings.last_update_seconds", 1572853649);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1572853397);
user_pref("services.settings.main.cfr-fxa.last_check", 1572853397);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1572853397);
user_pref("services.settings.main.hijack-blocklists.last_check", 1572853397);
user_pref("services.settings.main.language-dictionaries.last_check", 1572853397);
user_pref("services.settings.main.normandy-recipes.last_check", 1572853397);
user_pref("services.settings.main.sites-classification.last_check", 1572853397);
user_pref("services.settings.main.tippytop.last_check", 1572853397);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1572853397);
user_pref("services.settings.security.onecrl.checked", 1572853397);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1572853599);
user_pref("toolkit.startup.last_success", 1572853373);
user_pref("toolkit.telemetry.cachedClientID", "c0ffeec0-ffee-c0ff-eec0-ffeec0ffeec0");
user_pref("toolkit.telemetry.previousBuildID", "20190919142304");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
